### ISSUE TITLE
The presenting view doesn't return to the original size if the device was rotated.

### ISSUE THREAD

**Issue by trapper-** [kbpontius/iOSComposeAnimation#1]
Present the modal, rotate device, dismiss modal.

**Comment by kbpontius** [comment]
Thanks for adding to this @trapper-, I didn't see it. We have a newer PR that I just merged, you're welcome to add to that if you'd like. Just shoot me a message on the original thread and I'd be happy to merge it.

https://stackoverflow.com/questions/29017403/replicating-the-style-of-the-ios-mail-apps-compose-function/31056094?noredirect=1#comment89017249_31056094
